"""recipes

Revision ID: e669ff1ad55c
Revises: 73ec389cae2f
Create Date: 2025-11-04 23:52:08.202947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e669ff1ad55c'
down_revision: Union[str, Sequence[str], None] = '73ec389cae2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipes', 'cocktails', ['cocktail_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    # ### end Alembic commands ###
